name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple Command lines
        run: |
          echo "First command"
          echo "Second command
          
